---
abstract: 'Xymon Client Perl implemenation using POE. '
author:
  - 'T.J. Yang, C<< <tjyang2001 at gmail.com> >>'
  - 'T.J. Yang <tjyang2001@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  POE: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitor-Xymon-Client
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
